name: Example GitHub Workflow yml

on: ['push']

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Make backup
        uses: 'dianabarsan/superset-backup/.github/actions/superset-backup@main'
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          superset_link: ${{ secrets.SUPERSET_LINK }}
          superset_user: ${{ secrets.SUPERSET_USER }}
          superset_password: ${{ secrets.SUPERSET_PASSWORD }}
